global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'product-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['product-service:3002']

  - job_name: 'appointment-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['appointment-service:3003']

  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:3000']